# -*- coding: utf-8 -*-
"""Kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iceo5LYtDa0lKlZKtFSkVeMaD5gVKFW7
"""

#Hoàng Đắc Hùng
#msv 18103200013

from scipy.cluster.vq import kmeans, vq
from sklearn.cluster import KMeans
import pandas as pd
import matplotlib.pyplot as plt
# nhập các thư viện cần thiết

df = pd.read_csv("dataset.csv") # đọc dữ liệu từ tập dữ liệu dataset.csv
df.head() #hiển 5 đối tượng để kiểm tra tệp đã đúng hay chưa

# vẽ biểu đồ phân tán để trực quan hóa dữ liệu
plt.scatter(x=df['x'],y=df['y']) 
plt.xlabel('Label X')
plt.ylabel('Label Y')

km = KMeans(n_clusters=3) # đặt số lượng nhóm
y_predicted = km.fit_predict(df[['x','y']]) # tạo dự đoán
y_predicted

df['cluster']= y_predicted # thêm 1 cột có tên cluster (cụm) với 0 và 1 và 2 là các nhóm khác nhau
df

km.cluster_centers_ # dùng kmeans xác định lại tâm của các cụm

# vẽ lại biểu đồ và tâm để đễ trực quan
df1 = df[df.cluster==0]
df2 = df[df.cluster==1]
df3 = df[df.cluster==2]

#tạo màu cho các đối tượng
plt.scatter(df1['x'],df1['y'],color='green')
plt.scatter(df2['x'],df2['y'],color='red')
plt.scatter(df3['x'],df3['y'],color='yellow')
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*',label='Tâm cụm')#
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()

"""# Mục mới"""